server:
  port: 7081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 5
      linger.ms: 10
      batch.size: 32768
    producer:
      client-id: retail-producer